# Generated by Django 5.1 on 2024-10-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
